### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by tmaxmax** [tmaxmax/go-sse#7]
Here's what's planned for v1:
- [ ] Improve internal parsing API
  - [x] A refactor for better maintainability and correctness (#6)
  - [ ] Performance improvements (mainly concerning `internal/parser.Parser`)
- [ ] Improve server-side message creation API
  - [x] A refactor and simplification (#6)
  - [ ] Maybe a `Message.Writer`, which returns an `io.Writer` that can be used to write `data` fields to the event?
  - [ ] Performance (i.e. if there is something to be done with [this one tiny allocation](https://github.com/tmaxmax/go-sse/blob/master/message.go#L177-L186), so `sse.Message.WriteTo` is back at zero allocations)
- [ ] Improve server implementation
  - [ ] Check for correctness, revise tests
  - [ ] Re-evaluate API decisions – can it be designed better?
- [ ] Improve client
  - [ ] Change subscription API to use channels, provide a callback-based subscribe as a low-level alternative (this will simplify usage of the API)
  - [ ] Simplify and clean up internal logic – right now the code in [`client_connection.go`]() is quite contrived
  - [ ] Bring the API more in line with browsers' `EventSource`
  - [ ] Maybe reduce the configuration options?
  - [ ] Fix flaky tests ([Unsubscriptions](https://github.com/tmaxmax/go-sse/blob/eb740f5ebec8201afb4f553f292cd63d889a9db3/client_test.go#L424), [Subscription](https://github.com/tmaxmax/go-sse/blob/eb740f5ebec8201afb4f553f292cd63d889a9db3/client_test.go#L351), TODO: Find other such tests – there was one that was occasionally timing out)
- [ ] Documentation improvements
- [ ] Maybe another provider implementation?
- [ ] The test of time – try to grow usage of library, solve issues or requests that may pop up, and wait for things to be stable

**Comment by Pramodh-G** [comment]
Hey, I was searching around for only an SSE events parser - encoder/decoder. This was the only library I could find that isn't ancient - thanks for your work!

I'm using an openapi spec which generates ready to use API calls from client side - which is why I am not using the client in go-sse (it would take time to make it play well with openAPI generated code). However, I'm interested in using the code inside `internal/parser`. I could also help you with exposing it if you had a few ideas in mind.

I saw that the code in https://github.com/donovanhide/eventsource/blob/master/decoder.go, was much simpler and shorter than what you have written up - is there any advantage that I'm missing to your implementation? Please do let me know!

Thanks!
